echo Building 3rdParty libraries...
echo 	Building [Release]...

cd ../3rdparty/freetype
make

echo Deploying 3rdParty libraries...
echo Installing OpenAL...

sudo apt-get install libopenal-dev